"""add celery_task_id to projects

Revision ID: b48aaf102a6c
Revises: f34b83fec9f2
Create Date: 2026-03-22 00:37:26.951513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48aaf102a6c'
down_revision: Union[str, Sequence[str], None] = 'f34b83fec9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_projects', sa.Column('celery_task_id', sa.String(length=50), nullable=True, comment='Celery AsyncResult ID'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_projects', 'celery_task_id')
    # ### end Alembic commands ###
