"""initial tables

Revision ID: f34b83fec9f2
Revises: 
Create Date: 2026-03-22 00:22:11.276319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34b83fec9f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='User-friendly name'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='anthropic | openai | deepseek | custom'),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted API key'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='Custom OpenAI-compatible endpoint'),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original upload name'),
    sa.Column('file_path', sa.Text(), nullable=False, comment='Server-side storage path'),
    sa.Column('format', sa.String(length=10), nullable=False, comment='epub | pdf'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('total_blocks', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | parsed | error'),
    sa.Column('output_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False, comment='1-based chapter number'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('preview_text', sa.Text(), nullable=False, comment='First 200 chars'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | translating | completed | failed'),
    sa.ForeignKeyConstraint(['project_id'], ['translation_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False, comment='Order within chapter'),
    sa.Column('block_type', sa.String(length=10), nullable=False, comment='h1 | h2 | h3 | p'),
    sa.Column('text', sa.Text(), nullable=False, comment='Original text'),
    sa.Column('translated', sa.Text(), nullable=False, comment='Translated text'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending | translating | completed | failed'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_blocks')
    op.drop_table('chapters')
    op.drop_table('translation_projects')
    op.drop_table('translation_configs')
    # ### end Alembic commands ###
